import { Canvas } from '@react-three/fiber'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Canvas>
          <mesh>
            <boxBufferGeometry />
            <meshPhongMaterial />
          </mesh>
          <ambientLight args={[0xff0000]} intensity={0.1} />
          <directionalLight position={[0, 0, 5]} intensity={0.5} />
        </Canvas>
      </main>
    </>
  )
}
